### ISSUE TITLE
请问，可以自定义其中的城市数据源吗？

### ISSUE THREAD

**Issue by HenryZl** [zhifenx/JFCitySelector#1]
如题，如果只想展示某一个城市的详细区域信息，应该如何做呢？

**Comment by zhifenx** [comment]
这个你只需要用FMDB操作本地sqlite数据库即可

**Comment by zhifenx** [comment]
这个只需要使用FMDB操作本地sqlite数据库即可 @HenryZl

**Comment by HenryZl** [comment]
恩 ，了解了，需要自己添加更加详细的信息才行，谢谢！
