### ISSUE TITLE
b索引的找不到北京市  还是有点问题

### ISSUE THREAD

**Issue by liubang0909** [zhifenx/JFCitySelector#12]

**Comment by zhifenx** [comment]
行，我一会儿看看！

**Comment by zhifenx** [comment]
是v0.3.2最新版本吗？

**Comment by liubang0909** [comment]
热门城市的点击了没反应，切换区县是否可以关闭？“最近访问”标题的样式是否可以定制？里面的item的宽搞是否可以定制？UI自定义方面是否有更好的方式？只能在JFCSConfiguration范围内是否有点局限了？

**Comment by liubang0909** [comment]
对  刚看你回复了之后下载的

**Comment by liubang0909** [comment]
现在s里面没有北京和重庆了  应该是你新上传的版本

**Comment by zhifenx** [comment]
嗯，因为刚刚提了两个版本，会有延迟，那现在b索引里没北京吗？

**Comment by liubang0909** [comment]
对 没有

**Comment by liubang0909** [comment]
<img width="440" alt="截屏2020-07-29 下午6 56 06" src="https://user-images.githubusercontent.com/12213692/88791981-2bb4ee00-d1cd-11ea-96af-21af425bd7e1.png">c里面有三个城区

**Comment by zhifenx** [comment]
看了一下，北京是有的，只不过不是在b组的第一个。至于城区的问题，是因为不同城市下的城区名称上没做区分。

**Comment by zhifenx** [comment]
后面我区分一下

**Comment by zhifenx** [comment]
点击热门城市没反应的问题已修复，新增了切换城市按钮显示的开关，不同省市相同名称也做了区分；至于更符合自己需求的UI你可以自定义然后数据使用JFCSDataOperation，目前UI方面没有更新的计划。

**Comment by liubang0909** [comment]
好的 谢谢回复。。 代码写的很棒  没有警告  给你一个star
