### ISSUE TITLE
ios10 支持版本有点高，可以考虑降之ios 8 或 9

### ISSUE THREAD

**Issue by wlingf** [zhifenx/JFCitySelector#7]

**Comment by isdotjim** [comment]
搭个车...
想邀请你们来w3c.group创建项目对应的小组。w3c.group是类似知识星球的社群工具，但却不是知识付费性质的创作者社区，这里有相关的文章：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by liubang0909** [comment]
确实  为啥最低ios10？里面有特殊的10新出的API？低版本无法实现？

**Comment by zhifenx** [comment]
已支持到iOS 8.0
