### ISSUE TITLE
定位功能

### ISSUE THREAD

**Issue by dachong06** [zhifenx/JFCitySelector#8]
请教大佬，定位功能在哪里？运行了demo，没找到哪里有自动定位功能。手动选择和搜索做的挺好，就是没找到自动定位

**Comment by dachong06** [comment]
看了代码，没有定位功能。

**Comment by zhifenx** [comment]
是的，之前没加定位，觉得会和项目里的冲突，后来有人提，本来准备加的，但是最近太忙就没顾上！





------------------ 原始邮件 ------------------
发件人: dachong06 <notifications@github.com&gt;
发送时间: 2019年10月10日 10:15
收件人: zhifenx/JFCitySelector <JFCitySelector@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[zhifenx/JFCitySelector] 定位功能 (#8)




Closed #8.
